project_name: gofile
version: 2
builds:
  - id: android
    main: ./main.go
    goos:
      - android
    goarch:
      - arm64
    env:
      - CGO_ENABLED=0
    flags:
      - -trimpath
    ldflags:
      - "-s -w"

  - id: linux
    main: ./main.go
    goos:
      - linux
    goarch:
      - amd64
      - arm64
      - mips
      - mipsle
      - mips64
      - mips64le
      - loong64
    env:
      - CGO_ENABLED=0
    flags:
      - -trimpath
    ldflags:
      - "-s -w"

  - id: windows
    main: ./main.go
    goos:
      - windows
    goarch:
      - arm64
      - amd64
    env:
      - CGO_ENABLED=0
    flags:
      - -trimpath
    ldflags:
      - "-s -w"

  - id: darwin
    main: ./main.go
    goos:
      - darwin
    goarch:
      - arm64
      - amd64
    env:
      - CGO_ENABLED=0
    flags:
      - -trimpath
    ldflags:
      - "-s -w"

  - id: freebsd
    main: ./main.go
    goos:
      - freebsd
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0
    flags:
      - -trimpath
    ldflags:
      - "-s -w"

  - id: netbsd
    main: ./main.go
    goos:
      - netbsd
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0
    flags:
      - -trimpath
    ldflags:
      - "-s -w"

  - id: openbsd
    main: ./main.go
    goos:
      - openbsd
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0
    flags:
      - -trimpath
    ldflags:
      - "-s -w"

archives:
  - formats:
    - zip
    name_template: "gofile_{{.Os}}_{{.Arch}}"
    files:
      - README.md
      - LICENSE

checksum:
  name_template: "checksums.txt"

release:
  github:
    owner: lhear
    name: gofile
